name: Pull requests

on: pull_request
jobs:
  build:
    name: Build & test with "Node.js v${{ matrix.node-version }}" on "${{ matrix.os }}"

    strategy:
      fail-fast: false # don't cancel all jobs if some of them failed
      matrix:
        node-version: [
          12
        ]
        os: [
          ubuntu-latest,
          macOS-latest
        ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Setup tests
        run: npm run pretest
      - name: Test
        run: npm run test:coverage
      - name: Cleanup tests
        run: npm run posttest
